version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      runtime:
        patterns:
          - "!@types/*"
      dev:
        patterns:
          - "@types/*"
          - "eslint*"
          - "typescript"
