version: '3.8'

services:
  mice:
    container_name: mice-public
    image: sillyangel/mice:latest
    ports:
      - "40625:40625"
    environment:
      # Navidrome Server Configuration
      - NAVIDROME_URL=https://navi.sillyangel.dev
      - NAVIDROME_USERNAME=kryptonite
      - NAVIDROME_PASSWORD=kryptonite

      # PostHog Analytics
      - POSTHOG_KEY=phc_Sa39J7754MwaHrPxYiWnWETVSD3g1cU4nOplMGczRE9
      - POSTHOG_HOST=https://us.i.posthog.com

      # Application Port
      - PORT=40625
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:40625"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    restart: unless-stopped
